// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

nonisolated extension ShapeStyle where Self == ThemeShapeStyle<Color> {
    public static var brand: Self { .init(keyPath: \.colors.brand) }
    public static var accent: Self { .init(keyPath: \.colors.accent) }
    public static var onAccent: Self { .init(keyPath: \.colors.onAccent) }
    public static var attention: Self { .init(keyPath: \.colors.attention) }
    public static var onAttention: Self { .init(keyPath: \.colors.onAttention) }
    public static var active: Self { .init(keyPath: \.colors.active) }
    public static var onActive: Self { .init(keyPath: \.colors.onActive) }
    public static var success: Self { .init(keyPath: \.colors.success) }
    public static var onSuccess: Self { .init(keyPath: \.colors.onSuccess) }
    public static var info: Self { .init(keyPath: \.colors.info) }
    public static var onInfo: Self { .init(keyPath: \.colors.onInfo) }
    public static var warning: Self { .init(keyPath: \.colors.warning) }
    public static var onWarning: Self { .init(keyPath: \.colors.onWarning) }
    public static var error: Self { .init(keyPath: \.colors.error) }
    public static var onError: Self { .init(keyPath: \.colors.onError) }
    public static var neutral: Self { .init(keyPath: \.colors.neutral) }
    public static var surface: Self { .init(keyPath: \.colors.surface) }
}
