// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

nonisolated extension ShapeStyle where Self == ThemeShapeStyle<Gradient> {
    public static var accentGradient: Self { .init(keyPath: \.gradients.accentGradient) }
    public static var activeGradient: Self { .init(keyPath: \.gradients.activeGradient) }
    public static var attentionGradient: Self { .init(keyPath: \.gradients.attentionGradient) }
    public static var infoGradient: Self { .init(keyPath: \.gradients.infoGradient) }
    public static var warningGradient: Self { .init(keyPath: \.gradients.warningGradient) }
}
