// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

nonisolated public struct ThemeColors: Sendable, Codable, Equatable {
    public let brand: ThemeAdaptiveStyle<Color>
    public let accent: ThemeAdaptiveStyle<Color>
    public let onAccent: ThemeAdaptiveStyle<Color>
    public let attention: ThemeAdaptiveStyle<Color>
    public let onAttention: ThemeAdaptiveStyle<Color>
    public let active: ThemeAdaptiveStyle<Color>
    public let onActive: ThemeAdaptiveStyle<Color>
    public let success: ThemeAdaptiveStyle<Color>
    public let onSuccess: ThemeAdaptiveStyle<Color>
    public let info: ThemeAdaptiveStyle<Color>
    public let onInfo: ThemeAdaptiveStyle<Color>
    public let warning: ThemeAdaptiveStyle<Color>
    public let onWarning: ThemeAdaptiveStyle<Color>
    public let error: ThemeAdaptiveStyle<Color>
    public let onError: ThemeAdaptiveStyle<Color>
    public let neutral: ThemeAdaptiveStyle<Color>
    public let surface: ThemeAdaptiveStyle<Color>

    nonisolated public init(
        brand: ThemeAdaptiveStyle<Color>,
        accent: ThemeAdaptiveStyle<Color>,
        onAccent: ThemeAdaptiveStyle<Color>,
        attention: ThemeAdaptiveStyle<Color>,
        onAttention: ThemeAdaptiveStyle<Color>,
        active: ThemeAdaptiveStyle<Color>,
        onActive: ThemeAdaptiveStyle<Color>,
        success: ThemeAdaptiveStyle<Color>,
        onSuccess: ThemeAdaptiveStyle<Color>,
        info: ThemeAdaptiveStyle<Color>,
        onInfo: ThemeAdaptiveStyle<Color>,
        warning: ThemeAdaptiveStyle<Color>,
        onWarning: ThemeAdaptiveStyle<Color>,
        error: ThemeAdaptiveStyle<Color>,
        onError: ThemeAdaptiveStyle<Color>,
        neutral: ThemeAdaptiveStyle<Color>,
        surface: ThemeAdaptiveStyle<Color>
    ) {
        self.brand = brand
        self.accent = accent
        self.onAccent = onAccent
        self.attention = attention
        self.onAttention = onAttention
        self.active = active
        self.onActive = onActive
        self.success = success
        self.onSuccess = onSuccess
        self.info = info
        self.onInfo = onInfo
        self.warning = warning
        self.onWarning = onWarning
        self.error = error
        self.onError = onError
        self.neutral = neutral
        self.surface = surface
    }
}
