// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

extension ThemeColors {
    nonisolated public func copyWith(
        brand: ThemeAdaptiveStyle<Color>? = nil,
        accent: ThemeAdaptiveStyle<Color>? = nil,
        onAccent: ThemeAdaptiveStyle<Color>? = nil,
        attention: ThemeAdaptiveStyle<Color>? = nil,
        onAttention: ThemeAdaptiveStyle<Color>? = nil,
        active: ThemeAdaptiveStyle<Color>? = nil,
        onActive: ThemeAdaptiveStyle<Color>? = nil,
        success: ThemeAdaptiveStyle<Color>? = nil,
        onSuccess: ThemeAdaptiveStyle<Color>? = nil,
        info: ThemeAdaptiveStyle<Color>? = nil,
        onInfo: ThemeAdaptiveStyle<Color>? = nil,
        warning: ThemeAdaptiveStyle<Color>? = nil,
        onWarning: ThemeAdaptiveStyle<Color>? = nil,
        error: ThemeAdaptiveStyle<Color>? = nil,
        onError: ThemeAdaptiveStyle<Color>? = nil,
        neutral: ThemeAdaptiveStyle<Color>? = nil,
        surface: ThemeAdaptiveStyle<Color>? = nil
    ) -> ThemeColors {
        ThemeColors(
            brand: brand ?? self.brand,
            accent: accent ?? self.accent,
            onAccent: onAccent ?? self.onAccent,
            attention: attention ?? self.attention,
            onAttention: onAttention ?? self.onAttention,
            active: active ?? self.active,
            onActive: onActive ?? self.onActive,
            success: success ?? self.success,
            onSuccess: onSuccess ?? self.onSuccess,
            info: info ?? self.info,
            onInfo: onInfo ?? self.onInfo,
            warning: warning ?? self.warning,
            onWarning: onWarning ?? self.onWarning,
            error: error ?? self.error,
            onError: onError ?? self.onError,
            neutral: neutral ?? self.neutral,
            surface: surface ?? self.surface
        )
    }
}
