// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

nonisolated public struct Theme: Sendable, Codable, Equatable {
    public let colors: ThemeColors
    public let gradients: ThemeGradients

    nonisolated public init(
        colors: ThemeColors,
        gradients: ThemeGradients
    ) {
        self.colors = colors
        self.gradients = gradients
    }
}
