// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

nonisolated public struct ThemeGradients: Sendable, Codable, Equatable {
    public let accentGradient: ThemeAdaptiveStyle<Gradient>
    public let activeGradient: ThemeAdaptiveStyle<Gradient>
    public let attentionGradient: ThemeAdaptiveStyle<Gradient>
    public let infoGradient: ThemeAdaptiveStyle<Gradient>
    public let warningGradient: ThemeAdaptiveStyle<Gradient>

    nonisolated public init(
        accentGradient: ThemeAdaptiveStyle<Gradient>,
        activeGradient: ThemeAdaptiveStyle<Gradient>,
        attentionGradient: ThemeAdaptiveStyle<Gradient>,
        infoGradient: ThemeAdaptiveStyle<Gradient>,
        warningGradient: ThemeAdaptiveStyle<Gradient>
    ) {
        self.accentGradient = accentGradient
        self.activeGradient = activeGradient
        self.attentionGradient = attentionGradient
        self.infoGradient = infoGradient
        self.warningGradient = warningGradient
    }
}
