// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

extension Theme {
    nonisolated public func copyWith(
        colors: ThemeColors? = nil,
        gradients: ThemeGradients? = nil
    ) -> Theme {
        Theme(
            colors: colors ?? self.colors,
            gradients: gradients ?? self.gradients
        )
    }
}
