// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

extension ThemeGradients {
    nonisolated public func copyWith(
        accentGradient: ThemeAdaptiveStyle<Gradient>? = nil,
        activeGradient: ThemeAdaptiveStyle<Gradient>? = nil,
        attentionGradient: ThemeAdaptiveStyle<Gradient>? = nil,
        infoGradient: ThemeAdaptiveStyle<Gradient>? = nil,
        warningGradient: ThemeAdaptiveStyle<Gradient>? = nil
    ) -> ThemeGradients {
        ThemeGradients(
            accentGradient: accentGradient ?? self.accentGradient,
            activeGradient: activeGradient ?? self.activeGradient,
            attentionGradient: attentionGradient ?? self.attentionGradient,
            infoGradient: infoGradient ?? self.infoGradient,
            warningGradient: warningGradient ?? self.warningGradient
        )
    }
}
