// Generated by ThemeKit — do not edit

import SwiftUI
import ThemeKit

/// A SwiftUI view that renders all theme tokens as a visual palette.
public struct ThemePreview: View {

    public var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 24) {
                // MARK: - Colors
                VStack(alignment: .leading, spacing: 12) {
                    Text("Colors")
                        .font(.headline)
                    LazyVGrid(columns: [GridItem(.adaptive(minimum: 96))], spacing: 12) {
                            ColorSwatch(name: "brand", style: .brand)
                            ColorSwatch(name: "accent", style: .accent)
                            ColorSwatch(name: "onAccent", style: .onAccent)
                            ColorSwatch(name: "attention", style: .attention)
                            ColorSwatch(name: "onAttention", style: .onAttention)
                            ColorSwatch(name: "active", style: .active)
                            ColorSwatch(name: "onActive", style: .onActive)
                            ColorSwatch(name: "success", style: .success)
                            ColorSwatch(name: "onSuccess", style: .onSuccess)
                            ColorSwatch(name: "info", style: .info)
                            ColorSwatch(name: "onInfo", style: .onInfo)
                            ColorSwatch(name: "warning", style: .warning)
                            ColorSwatch(name: "onWarning", style: .onWarning)
                            ColorSwatch(name: "error", style: .error)
                            ColorSwatch(name: "onError", style: .onError)
                            ColorSwatch(name: "neutral", style: .neutral)
                            ColorSwatch(name: "surface", style: .surface)
                    }
                }
                // MARK: - Gradients
                VStack(alignment: .leading, spacing: 12) {
                    Text("Gradients")
                        .font(.headline)
                    LazyVGrid(columns: [GridItem(.adaptive(minimum: 96))], spacing: 12) {
                            GradientStrip(name: "accentGradient", style: .accentGradient)
                            GradientStrip(name: "activeGradient", style: .activeGradient)
                            GradientStrip(name: "attentionGradient", style: .attentionGradient)
                            GradientStrip(name: "infoGradient", style: .infoGradient)
                            GradientStrip(name: "warningGradient", style: .warningGradient)
                    }
                }
            }
            .padding()
        }
    }
}

#Preview {
    ThemePreview()
}

// MARK: - Preview Components

private struct ColorSwatch<Style: ShapeStyle>: View {
    let name: String
    let style: Style

    var body: some View {
        VStack(alignment: .leading, spacing: 4) {
            RoundedRectangle(cornerRadius: 8)
                .fill(style)
                .frame(height: 32)

            Text(name)
                .font(.caption)
                .lineLimit(1)
                .foregroundStyle(.secondary)
        }
    }
}

private struct GradientStrip<Style: ShapeStyle>: View {
    let name: String
    let style: Style

    var body: some View {
        VStack(alignment: .leading, spacing: 4) {
            RoundedRectangle(cornerRadius: 8)
                .fill(style)
                .frame(height: 48)

            Text(name)
                .font(.caption)
                .lineLimit(1)
                .foregroundStyle(.secondary)
        }
    }
}
